### ISSUE TITLE
Addition to the our basic calculator

### ISSUE THREAD

**Issue by NorbertJay** [NorbertJay/Calculator#9]
Kay naa naman ta basic calc, mag add nata ug other functions. Try nato add as many as we can and know. Nakalimtan pud diay ang open ug close brackets sa basic calc. Add nlng nato to siya sa atung upgraded na calc. Goal nato is makahimo ug scical or close sa scical. Thank you

**Comment by maevx** [comment]
dili na siya iadd sa basic calc ang close ug open parenthesis?

**Comment by maevx** [comment]
> Kay naa naman ta basic calc, mag add nata ug other functions. Try nato add as many as we can and know. Nakalimtan pud diay ang open ug close brackets sa basic calc. Add nlng nato to siya sa atung upgraded na calc. Goal nato is makahimo ug scical or close sa scical. Thank you

dili na siya iadd sa basic calc ang close ug open parenthesis?

**Comment by NorbertJay** [comment]
dili na guro lotte. Naa naman siya sa final calc nato. Slr
